# Generated by Django 4.2.1 on 2023-05-27 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customer_iriksha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer_iriksha',
        ),
    ]
